# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('is_successful', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('time_executed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('stock_type', models.CharField(max_length=20)),
                ('is_sell', models.BooleanField(default=True)),
                ('time_executed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'P', b'In Progress'), (b'C', b'Completed'), (b'F', b'Failed'), (b'S', b'Paused'), (b'X', b'Cancelled')], default=b'P', max_length=1)),
                ('progress', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='childorder',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.ParentOrder'),
        ),
    ]
