# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 08:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.AddField(
            model_name='noteauthorization',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notetaker.Note'),
        ),
        migrations.AddField(
            model_name='noteauthorization',
            name='note_initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_authorizing', to='notetaker.NoteUser'),
        ),
        migrations.AddField(
            model_name='noteauthorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notetaker.NoteUser'),
        ),
        migrations.AddField(
            model_name='note',
            name='permissions',
            field=models.ManyToManyField(through='notetaker.NoteAuthorization', to='notetaker.NoteUser'),
        ),
    ]
