# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0002_auto_20170402_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
