# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:45
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('social_django', '0006_partial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('notetaker', '0003_texteditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='NoteUser',
        ),
        migrations.CreateModel(
            name='NoteUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
